#UTC Generated by Django 3.1.7 on 2021-04-18 16:23

from django.db import migrations


def insert_data(apps, schema_editor):
    EventType = apps.get_model('events', 'EventType')

    EventType.objects.bulk_create([
        EventType(name='School'),
    ])


def delete_data(apps, schema_editor):
    EventType= apps.get_model('events', 'EventType')
    EventType.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_data, delete_data),
    ]
