# Generated by Django 3.2 on 2021-05-20 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210520_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='qr_id',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
